# Generated by Django 5.1.3 on 2024-12-07 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('9am-10am', '9:00 AM - 10:00 AM'), ('10am-11am', '10:00 AM - 11:00 AM'), ('2pm-3pm', '2:00 PM - 3:00 PM'), ('3pm-4pm', '3:00 PM - 4:00 PM')], max_length=50)),
                ('appointment_type', models.CharField(choices=[('consultation', 'Consultations'), ('nutrition-counseling', 'Nutrition Counseling')], max_length=50)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('preferred_date', 'preferred_time')},
            },
        ),
    ]
