# Generated by Django 5.1.3 on 2024-12-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(),
        ),
    ]
